# Generated by Django 4.2.6 on 2025-04-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', help_text='Цветовая тема интерфейса', max_length=10)),
                ('density', models.CharField(choices=[('comfortable', 'Комфортная'), ('compact', 'Компактная')], default='comfortable', help_text='Плотность интерфейса', max_length=12)),
                ('tooltips_on', models.BooleanField(default=True, help_text='Показывать подсказки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
