# Generated by Django 4.2.6 on 2025-04-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа полей')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('date', 'Дата'), ('file', 'Файл')], max_length=10, verbose_name='Тип')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='fields.fieldgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='field_values/')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.fielddefinition')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'definition')},
            },
        ),
    ]
