# Generated by Django 4.2.6 on 2025-05-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeefieldvalue'),
        ('fields', '0002_fieldgroup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinitionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values_in_fields', to='employees.employee')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='fields.fielddefinition')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeFieldValue',
        ),
    ]
