# Generated by Django 4.2.6 on 2025-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_expiry_days', models.PositiveIntegerField(help_text='Через сколько дней по умолчанию истекает документ этого типа')),
            ],
        ),
    ]
