# Generated by Django 4.2.6 on 2025-04-23 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя тега')),
                ('system', models.BooleanField(default=False, verbose_name='Системный')),
            ],
        ),
        migrations.CreateModel(
            name='TagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Запрошенный тег')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_tag_requests', related_query_name='tag_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
