# Generated by Django 4.2.6 on 2025-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_fielddefinitionvalue_delete_employeefieldvalue'),
        ('employees', '0003_employeefieldvalue'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='employees.direction'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='roles.position'),
        ),
        migrations.CreateModel(
            name='RoleFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('field_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.fieldgroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='roles.role')),
            ],
            options={
                'unique_together': {('role', 'field_group')},
            },
        ),
    ]
